(load (concat (file-name-directory load-file-name) "edit-utils.el"))
(load (concat (file-name-directory load-file-name) "new-shell.el"))
(load (concat (file-name-directory load-file-name) "project-nav.el"))
(load (concat (file-name-directory load-file-name) "rails-nav.el"))
(load (concat (file-name-directory load-file-name) "java-nav.el"))
(load (concat (file-name-directory load-file-name) "run-rspec.el"))
